name: Build JAR with Maven

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17.0.9
          distribution: 'liberica'
          java-package: jdk+fx
          cache: 'maven'

      - name: Build JAR with Maven
        run: mvn -B clean package --file pom.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: target/dependency/mips-emulator*dependencies*.jar
