name: Test and build JAR

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Set up Ubuntu
        run: sudo apt-get update

      - name: Set up Java 11 x86
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: 'x64'

      - name: Test and build x86_64 JAR
        run: |
          mkdir x86
          mvn --batch-mode --update-snapshots verify --file pom.xml
          cp target/*.jar x86/

      - name: Set up Java 11 ARM64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: 'aarch64'

      - name: Test and build ARM64 JAR
        run: |
          mkdir ARM64
          mvn --batch-mode --update-snapshots verify --file pom.xml
          cp target/*.jar ARM64/

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: |
            x86/*.jar
            ARM64/*.jar

      # https://github.com/codespell-project/actions-codespell
      - name: CSpell
        uses: streetsidesoftware/cspell-action@v3
        with:
          config: "cspell.json"
