name: Repo visualizer

on:
  push:
    branches: [ main, installsh ]
  pull_request:
    branches: [ main, installsh ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update diagram
      uses: githubocto/repo-visualizer@main
      with:
        output_file: 'docs/structure.svg'
        excluded_paths: 'target,dist,node_modules'
